// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeeicbshmnqwswkpzlmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZWljYnNobW5xd3N3a3B6bG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODMyMTcsImV4cCI6MjA3NTI1OTIxN30.jycxFKZYaQPXfrKHSvsai5qGslU6E-we_TSxM89LEIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});