// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtlmyqfjlspqxscoaamd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0bG15cWZqbHNwcXhzY29hYW1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMDQzNjcsImV4cCI6MjA3NTc4MDM2N30.zOECjQ4TswItBLPd6sme9_aJS0h53RANuxWpECOEcvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
